[program:queue-default]
directory=/var/www/html
command=/bin/sh -lc 'exec php -d memory_limit=512M artisan queue:work database --queue=default --sleep=2 --tries=3 --timeout=120 --max-time=3600 --max-jobs=500 --backoff=5 --memory=256 --json'
user=www-data
numprocs=2
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
stopasgroup=true
killasgroup=true

[program:queue-vereinsflieger-low]
directory=/var/www/html
command=/bin/sh -lc 'exec php -d memory_limit=512M artisan queue:work database --queue=vereinsflieger-low --sleep=2 --tries=10 --timeout=120 --max-time=3600 --max-jobs=500 --backoff=5 --memory=256 --json'
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
stopasgroup=true
killasgroup=true
