[program:queue]
directory=/var/www/html
command=/bin/sh -lc 'exec php artisan queue:work --json --memory=512'
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
stopasgroup=true
killasgroup=true
